//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crash.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crash.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation ({0}).
        /// </summary>
        public static string AnimationEntryController_Text {
            get {
                return ResourceManager.GetString("AnimationEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Chunk.
        /// </summary>
        public static string ChunkController_AcDelete {
            get {
                return ResourceManager.GetString("ChunkController_AcDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Chunk &quot;{0}&quot;.
        /// </summary>
        public static string ChunkController_AcDeleteWithEName {
            get {
                return ResourceManager.GetString("ChunkController_AcDeleteWithEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprocess Chunk.
        /// </summary>
        public static string ChunkController_AcDeprocess {
            get {
                return ResourceManager.GetString("ChunkController_AcDeprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprocess Chunk &quot;{0}&quot;.
        /// </summary>
        public static string ChunkController_AcDeprocessWithEName {
            get {
                return ResourceManager.GetString("ChunkController_AcDeprocessWithEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colored Animation ({0}).
        /// </summary>
        public static string ColoredAnimationEntryController_Text {
            get {
                return ResourceManager.GetString("ColoredAnimationEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No options available..
        /// </summary>
        public static string Controller_NoOptionsAvailable {
            get {
                return ResourceManager.GetString("Controller_NoOptionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo ({0}).
        /// </summary>
        public static string DemoEntryController_Text {
            get {
                return ResourceManager.GetString("DemoEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string EntityController_Text {
            get {
                return ResourceManager.GetString("EntityController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Entry.
        /// </summary>
        public static string EntryChunkController_AcAddNew {
            get {
                return ResourceManager.GetString("EntryChunkController_AcAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Entry.
        /// </summary>
        public static string EntryChunkController_AcImport {
            get {
                return ResourceManager.GetString("EntryChunkController_AcImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Entry &quot;{0}&quot;.
        /// </summary>
        public static string EntryController_AcDelete {
            get {
                return ResourceManager.GetString("EntryController_AcDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprocess Entry &quot;{0}&quot;.
        /// </summary>
        public static string EntryController_AcDeprocess {
            get {
                return ResourceManager.GetString("EntryController_AcDeprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Entry &quot;{0}&quot;.
        /// </summary>
        public static string EntryController_AcExport {
            get {
                return ResourceManager.GetString("EntryController_AcExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Entry &quot;{0}&quot;.
        /// </summary>
        public static string EntryController_AcRename {
            get {
                return ResourceManager.GetString("EntryController_AcRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame.
        /// </summary>
        public static string FrameController_Text {
            get {
                return ResourceManager.GetString("FrameController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a game version from the list below. NTSC-U, NTSC-J, and PAL are all supported..
        /// </summary>
        public static string GameVersionForm_Message {
            get {
                return ResourceManager.GetString("GameVersionForm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerelease Versions.
        /// </summary>
        public static string GameVersionForm_Prerelease {
            get {
                return ResourceManager.GetString("GameVersionForm_Prerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Versions.
        /// </summary>
        public static string GameVersionForm_Release {
            get {
                return ResourceManager.GetString("GameVersionForm_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Version Selection.
        /// </summary>
        public static string GameVersionForm_Text {
            get {
                return ResourceManager.GetString("GameVersionForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prototype GOOL ({0}).
        /// </summary>
        public static string GOOLv0EntryController_Text {
            get {
                return ResourceManager.GetString("GOOLv0EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOL ({0}).
        /// </summary>
        public static string GOOLv1EntryController_Text {
            get {
                return ResourceManager.GetString("GOOLv1EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOLv2 ({0}).
        /// </summary>
        public static string GOOLv2EntryController_Text {
            get {
                return ResourceManager.GetString("GOOLv2EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOLv3 ({0}).
        /// </summary>
        public static string GOOLv3EntryController_Text {
            get {
                return ResourceManager.GetString("GOOLv3EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image ({0}).
        /// </summary>
        public static string ImageEntryController_Text {
            get {
                return ResourceManager.GetString("ImageEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ItemController_Text {
            get {
                return ResourceManager.GetString("ItemController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map ({0}).
        /// </summary>
        public static string MapEntryController_Text {
            get {
                return ResourceManager.GetString("MapEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed Model ({0}).
        /// </summary>
        public static string ModelEntryController_Compressed_Text {
            get {
                return ResourceManager.GetString("ModelEntryController_Compressed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model ({0}).
        /// </summary>
        public static string ModelEntryController_Text {
            get {
                return ResourceManager.GetString("ModelEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music ({0}).
        /// </summary>
        public static string MusicEntryController_Text {
            get {
                return ResourceManager.GetString("MusicEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk {0}.
        /// </summary>
        public static string NormalChunkController_Text {
            get {
                return ResourceManager.GetString("NormalChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Chunk.
        /// </summary>
        public static string NSFController_AcAddNormalChunk {
            get {
                return ResourceManager.GetString("NSFController_AcAddNormalChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Old Sound Chunk.
        /// </summary>
        public static string NSFController_AcAddOldSoundChunk {
            get {
                return ResourceManager.GetString("NSFController_AcAddOldSoundChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sound Chunk.
        /// </summary>
        public static string NSFController_AcAddSoundChunk {
            get {
                return ResourceManager.GetString("NSFController_AcAddSoundChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Speech Chunk.
        /// </summary>
        public static string NSFController_AcAddSpeechChunk {
            get {
                return ResourceManager.GetString("NSFController_AcAddSpeechChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Wavebank Chunk.
        /// </summary>
        public static string NSFController_AcAddWavebankChunk {
            get {
                return ResourceManager.GetString("NSFController_AcAddWavebankChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Box Count.
        /// </summary>
        public static string NSFController_AcFixBoxCount {
            get {
                return ResourceManager.GetString("NSFController_AcFixBoxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Nitro Detonators.
        /// </summary>
        public static string NSFController_AcFixDetonator {
            get {
                return ResourceManager.GetString("NSFController_AcFixDetonator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Chunk.
        /// </summary>
        public static string NSFController_AcImportChunk {
            get {
                return ResourceManager.GetString("NSFController_AcImportChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Level Scenery.
        /// </summary>
        public static string NSFController_AcShowLevel {
            get {
                return ResourceManager.GetString("NSFController_AcShowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSF File.
        /// </summary>
        public static string NSFController_Text {
            get {
                return ResourceManager.GetString("NSFController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Animation ({0}).
        /// </summary>
        public static string OldAnimationEntryController_Text {
            get {
                return ResourceManager.GetString("OldAnimationEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string OldCameraController_Text {
            get {
                return ResourceManager.GetString("OldCameraController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} ({1}-{2}).
        /// </summary>
        public static string OldEntityController_Text {
            get {
                return ResourceManager.GetString("OldEntityController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Model ({0}).
        /// </summary>
        public static string OldModelEntryController_Text {
            get {
                return ResourceManager.GetString("OldModelEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Music ({0}).
        /// </summary>
        public static string OldMusicEntryController_Text {
            get {
                return ResourceManager.GetString("OldMusicEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Scenery ({0}).
        /// </summary>
        public static string OldSceneryEntryController_Text {
            get {
                return ResourceManager.GetString("OldSceneryEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Sort List ({0}).
        /// </summary>
        public static string OldSLSTEntryController_Text {
            get {
                return ResourceManager.GetString("OldSLSTEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Sound Chunk {0}.
        /// </summary>
        public static string OldSoundChunkController_Text {
            get {
                return ResourceManager.GetString("OldSoundChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Zone ({0}).
        /// </summary>
        public static string OldZoneEntryController_Text {
            get {
                return ResourceManager.GetString("OldZoneEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette ({0}).
        /// </summary>
        public static string PaletteEntryController_Text {
            get {
                return ResourceManager.GetString("PaletteEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prototype Animation ({0}).
        /// </summary>
        public static string ProtoAnimationEntryController_Text {
            get {
                return ResourceManager.GetString("ProtoAnimationEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prototype Scenery ({0}).
        /// </summary>
        public static string ProtoSceneryEntryController_Text {
            get {
                return ResourceManager.GetString("ProtoSceneryEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proto Zone ({0}).
        /// </summary>
        public static string ProtoZoneEntryController_Text {
            get {
                return ResourceManager.GetString("ProtoZoneEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery ({0}).
        /// </summary>
        public static string SceneryEntryController_Text {
            get {
                return ResourceManager.GetString("SceneryEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort List ({0}).
        /// </summary>
        public static string SLSTEntryController_Text {
            get {
                return ResourceManager.GetString("SLSTEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Chunk {0}.
        /// </summary>
        public static string SoundChunkController_Text {
            get {
                return ResourceManager.GetString("SoundChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound ({0}).
        /// </summary>
        public static string SoundEntryController_Text {
            get {
                return ResourceManager.GetString("SoundEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Chunk {0}.
        /// </summary>
        public static string SpeechChunkController_Text {
            get {
                return ResourceManager.GetString("SpeechChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech ({0}).
        /// </summary>
        public static string SpeechEntryController_Text {
            get {
                return ResourceManager.GetString("SpeechEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T11 ({0}).
        /// </summary>
        public static string T11EntryController_Text {
            get {
                return ResourceManager.GetString("T11EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T15 ({0}).
        /// </summary>
        public static string T15EntryController_Text {
            get {
                return ResourceManager.GetString("T15EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T17 ({0}).
        /// </summary>
        public static string T17EntryController_Text {
            get {
                return ResourceManager.GetString("T17EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T1 ({0}).
        /// </summary>
        public static string T1EntryController_Text {
            get {
                return ResourceManager.GetString("T1EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T21 ({0}).
        /// </summary>
        public static string T21EntryController_Text {
            get {
                return ResourceManager.GetString("T21EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T6 ({0}).
        /// </summary>
        public static string T6EntryController_Text {
            get {
                return ResourceManager.GetString("T6EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open viewer.
        /// </summary>
        public static string TextureChunkController_AcOpenViewer {
            get {
                return ResourceManager.GetString("TextureChunkController_AcOpenViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate Checksum.
        /// </summary>
        public static string TextureChunkController_AcRecalcChecksum {
            get {
                return ResourceManager.GetString("TextureChunkController_AcRecalcChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Chunk.
        /// </summary>
        public static string TextureChunkController_AcRename {
            get {
                return ResourceManager.GetString("TextureChunkController_AcRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Chunk {1} ({0}).
        /// </summary>
        public static string TextureChunkController_Text {
            get {
                return ResourceManager.GetString("TextureChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Chunk.
        /// </summary>
        public static string UnprocessedChunkController_AcProcess {
            get {
                return ResourceManager.GetString("UnprocessedChunkController_AcProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprocessed Chunk {1} (T{0}).
        /// </summary>
        public static string UnprocessedChunkController_Text {
            get {
                return ResourceManager.GetString("UnprocessedChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Entry &quot;{0}&quot;.
        /// </summary>
        public static string UnprocessedEntryController_AcProcess {
            get {
                return ResourceManager.GetString("UnprocessedEntryController_AcProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprocessed T{0} ({1}).
        /// </summary>
        public static string UnprocessedEntryController_Text {
            get {
                return ResourceManager.GetString("UnprocessedEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavebank Chunk {0}.
        /// </summary>
        public static string WavebankChunkController_Text {
            get {
                return ResourceManager.GetString("WavebankChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavebank ({0}).
        /// </summary>
        public static string WavebankEntryController_Text {
            get {
                return ResourceManager.GetString("WavebankEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Entity.
        /// </summary>
        public static string ZoneEntryController_AcAddEntity {
            get {
                return ResourceManager.GetString("ZoneEntryController_AcAddEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone ({0}).
        /// </summary>
        public static string ZoneEntryController_Text {
            get {
                return ResourceManager.GetString("ZoneEntryController_Text", resourceCulture);
            }
        }
    }
}
