//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crash.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crash.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Chunk.
        /// </summary>
        internal static string ChunkController_AcDelete {
            get {
                return ResourceManager.GetString("ChunkController_AcDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Chunk &quot;{0}&quot;.
        /// </summary>
        internal static string ChunkController_AcDeleteWithEName {
            get {
                return ResourceManager.GetString("ChunkController_AcDeleteWithEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprocess Chunk.
        /// </summary>
        internal static string ChunkController_AcDeprocess {
            get {
                return ResourceManager.GetString("ChunkController_AcDeprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprocess Chunk &quot;{0}&quot;.
        /// </summary>
        internal static string ChunkController_AcDeprocessWithEName {
            get {
                return ResourceManager.GetString("ChunkController_AcDeprocessWithEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No options available..
        /// </summary>
        internal static string Controller_NoOptionsAvailable {
            get {
                return ResourceManager.GetString("Controller_NoOptionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutscene Animation ({0}).
        /// </summary>
        internal static string CutsceneAnimationEntryController_Text {
            get {
                return ResourceManager.GetString("CutsceneAnimationEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo ({0}).
        /// </summary>
        internal static string DemoEntryController_Text {
            get {
                return ResourceManager.GetString("DemoEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Entry &quot;{0}&quot;.
        /// </summary>
        internal static string EntryController_AcDelete {
            get {
                return ResourceManager.GetString("EntryController_AcDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprocess Entry &quot;{0}&quot;.
        /// </summary>
        internal static string EntryController_AcDeprocess {
            get {
                return ResourceManager.GetString("EntryController_AcDeprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a game version from the list below. NTSC-U, NTSC-J, and PAL are all supported..
        /// </summary>
        internal static string GameVersionForm_Message {
            get {
                return ResourceManager.GetString("GameVersionForm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerelease Versions.
        /// </summary>
        internal static string GameVersionForm_Prerelease {
            get {
                return ResourceManager.GetString("GameVersionForm_Prerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Versions.
        /// </summary>
        internal static string GameVersionForm_Release {
            get {
                return ResourceManager.GetString("GameVersionForm_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Version Selection.
        /// </summary>
        internal static string GameVersionForm_Text {
            get {
                return ResourceManager.GetString("GameVersionForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model ({0}).
        /// </summary>
        internal static string ModelEntryController_Text {
            get {
                return ResourceManager.GetString("ModelEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music ({0}).
        /// </summary>
        internal static string MusicEntryController_Text {
            get {
                return ResourceManager.GetString("MusicEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk.
        /// </summary>
        internal static string NormalChunkController_Text {
            get {
                return ResourceManager.GetString("NormalChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Chunk.
        /// </summary>
        internal static string NSFController_AcAddNormalChunk {
            get {
                return ResourceManager.GetString("NSFController_AcAddNormalChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSF File.
        /// </summary>
        internal static string NSFController_Text {
            get {
                return ResourceManager.GetString("NSFController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Animation ({0}).
        /// </summary>
        internal static string OldAnimationEntryController_Text {
            get {
                return ResourceManager.GetString("OldAnimationEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Model ({0}).
        /// </summary>
        internal static string OldModelEntryController_Text {
            get {
                return ResourceManager.GetString("OldModelEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Music ({0}).
        /// </summary>
        internal static string OldMusicEntryController_Text {
            get {
                return ResourceManager.GetString("OldMusicEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Scenery ({0}).
        /// </summary>
        internal static string OldSceneryEntryController_Text {
            get {
                return ResourceManager.GetString("OldSceneryEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Sound Chunk.
        /// </summary>
        internal static string OldSoundChunkController_Text {
            get {
                return ResourceManager.GetString("OldSoundChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old T15 ({0}).
        /// </summary>
        internal static string OldT15EntryController_Text {
            get {
                return ResourceManager.GetString("OldT15EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old T17 ({0}).
        /// </summary>
        internal static string OldT17EntryController_Text {
            get {
                return ResourceManager.GetString("OldT17EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Zone ({0}).
        /// </summary>
        internal static string OldZoneEntryController_Text {
            get {
                return ResourceManager.GetString("OldZoneEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette ({0}).
        /// </summary>
        internal static string PaletteEntryController_Text {
            get {
                return ResourceManager.GetString("PaletteEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proto Zone ({0}).
        /// </summary>
        internal static string ProtoZoneEntryController_Text {
            get {
                return ResourceManager.GetString("ProtoZoneEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery ({0}).
        /// </summary>
        internal static string SceneryEntryController_Text {
            get {
                return ResourceManager.GetString("SceneryEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLST ({0}).
        /// </summary>
        internal static string SLSTEntryController_Text {
            get {
                return ResourceManager.GetString("SLSTEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Chunk.
        /// </summary>
        internal static string SoundChunkController_Text {
            get {
                return ResourceManager.GetString("SoundChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound ({0}).
        /// </summary>
        internal static string SoundEntryController_Text {
            get {
                return ResourceManager.GetString("SoundEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Chunk.
        /// </summary>
        internal static string SpeechChunkController_Text {
            get {
                return ResourceManager.GetString("SpeechChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech ({0}).
        /// </summary>
        internal static string SpeechEntryController_Text {
            get {
                return ResourceManager.GetString("SpeechEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T11 ({0}).
        /// </summary>
        internal static string T11EntryController_Text {
            get {
                return ResourceManager.GetString("T11EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T15 ({0}).
        /// </summary>
        internal static string T15EntryController_Text {
            get {
                return ResourceManager.GetString("T15EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T17 ({0}).
        /// </summary>
        internal static string T17EntryController_Text {
            get {
                return ResourceManager.GetString("T17EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T1 ({0}).
        /// </summary>
        internal static string T1EntryController_Text {
            get {
                return ResourceManager.GetString("T1EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T21 ({0}).
        /// </summary>
        internal static string T21EntryController_Text {
            get {
                return ResourceManager.GetString("T21EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T6 ({0}).
        /// </summary>
        internal static string T6EntryController_Text {
            get {
                return ResourceManager.GetString("T6EntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Chunk ({0}).
        /// </summary>
        internal static string TextureChunkController_Text {
            get {
                return ResourceManager.GetString("TextureChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Chunk.
        /// </summary>
        internal static string UnprocessedChunkController_AcProcess {
            get {
                return ResourceManager.GetString("UnprocessedChunkController_AcProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprocessed Chunk.
        /// </summary>
        internal static string UnprocessedChunkController_Text {
            get {
                return ResourceManager.GetString("UnprocessedChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprocessed ({0}).
        /// </summary>
        internal static string UnprocessedEntryController_Text {
            get {
                return ResourceManager.GetString("UnprocessedEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavebank Chunk.
        /// </summary>
        internal static string WavebankChunkController_Text {
            get {
                return ResourceManager.GetString("WavebankChunkController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavebank ({0}).
        /// </summary>
        internal static string WavebankEntryController_Text {
            get {
                return ResourceManager.GetString("WavebankEntryController_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone ({0}).
        /// </summary>
        internal static string ZoneEntryController_Text {
            get {
                return ResourceManager.GetString("ZoneEntryController_Text", resourceCulture);
            }
        }
    }
}
