//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrashEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrashEdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Confirmation Prompt.
        /// </summary>
        internal static string Close_ConfirmationPrompt {
            get {
                return ResourceManager.GetString("Close_ConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the NSF file?.
        /// </summary>
        internal static string CloseNSF {
            get {
                return ResourceManager.GetString("CloseNSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Computer_File_053 {
            get {
                object obj = ResourceManager.GetObject("Computer_File_053", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Computer_File_063 {
            get {
                object obj = ResourceManager.GetObject("Computer_File_063", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Computer_File_064 {
            get {
                object obj = ResourceManager.GetObject("Computer_File_064", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Computer_File_068 {
            get {
                object obj = ResourceManager.GetObject("Computer_File_068", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Config_chkAnimGrid {
            get {
                return ResourceManager.GetString("Config_chkAnimGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display frame collision by default.
        /// </summary>
        internal static string Config_chkCollisionDisplay {
            get {
                return ResourceManager.GetString("Config_chkCollisionDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Patch NSD) Delete non-existent entries from load lists.
        /// </summary>
        internal static string Config_chkDeleteInvalidEntries {
            get {
                return ResourceManager.GetString("Config_chkDeleteInvalidEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display normals.
        /// </summary>
        internal static string Config_chkNormalDisplay {
            get {
                return ResourceManager.GetString("Config_chkNormalDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Patch NSD) Always save NSF after NSD patching.
        /// </summary>
        internal static string Config_chkPatchNSDSavesNSF {
            get {
                return ResourceManager.GetString("Config_chkPatchNSDSavesNSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Crash 3) Used saved animation-model links.
        /// </summary>
        internal static string Config_chkUseAnimLinks {
            get {
                return ResourceManager.GetString("Config_chkUseAnimLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        internal static string Config_cmdReset {
            get {
                return ResourceManager.GetString("Config_cmdReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation Viewer World Grid.
        /// </summary>
        internal static string Config_fraAnimGrid {
            get {
                return ResourceManager.GetString("Config_fraAnimGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Color.
        /// </summary>
        internal static string Config_fraClearCol {
            get {
                return ResourceManager.GetString("Config_fraClearCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language (requires restart).
        /// </summary>
        internal static string Config_FraLang {
            get {
                return ResourceManager.GetString("Config_FraLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Window Size.
        /// </summary>
        internal static string Config_fraSize {
            get {
                return ResourceManager.GetString("Config_fraSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Config_lblAnimGrid {
            get {
                return ResourceManager.GetString("Config_lblAnimGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Config_lblH {
            get {
                return ResourceManager.GetString("Config_lblH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Config_lblW {
            get {
                return ResourceManager.GetString("Config_lblW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extra feature: VB size is invalid.
        /// </summary>
        internal static string ConvertVAB_Error {
            get {
                return ResourceManager.GetString("ConvertVAB_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extra feature: VB size does not match size specified in VH.
        /// </summary>
        internal static string ConvertVHVB_Error {
            get {
                return ResourceManager.GetString("ConvertVHVB_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in a Model (or Compressed Model) name and press Enter..
        /// </summary>
        internal static string Crash3AnimationSelector_Desc {
            get {
                return ResourceManager.GetString("Crash3AnimationSelector_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled (Bonus).
        /// </summary>
        internal static string EntityBox_ChkBonusBoxCount {
            get {
                return ResourceManager.GetString("EntityBox_ChkBonusBoxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string EntityBox_ChkEnabled {
            get {
                return ResourceManager.GetString("EntityBox_ChkEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        internal static string EntityBox_ChkHex {
            get {
                return ResourceManager.GetString("EntityBox_ChkHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string EntityBox_CmdAdd {
            get {
                return ResourceManager.GetString("EntityBox_CmdAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append.
        /// </summary>
        internal static string EntityBox_CmdAppend {
            get {
                return ResourceManager.GetString("EntityBox_CmdAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string EntityBox_cmdClearAllVictims {
            get {
                return ResourceManager.GetString("EntityBox_cmdClearAllVictims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string EntityBox_CmdInsert {
            get {
                return ResourceManager.GetString("EntityBox_CmdInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolate.
        /// </summary>
        internal static string EntityBox_CmdInterpolate {
            get {
                return ResourceManager.GetString("EntityBox_CmdInterpolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify List Integrity.
        /// </summary>
        internal static string EntityBox_cmdLoadListVerify {
            get {
                return ResourceManager.GetString("EntityBox_cmdLoadListVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string EntityBox_CmdNext {
            get {
                return ResourceManager.GetString("EntityBox_CmdNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Payload.
        /// </summary>
        internal static string EntityBox_cmdPayload {
            get {
                return ResourceManager.GetString("EntityBox_cmdPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string EntityBox_CmdPrevious {
            get {
                return ResourceManager.GetString("EntityBox_CmdPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string EntityBox_CmdRemove {
            get {
                return ResourceManager.GetString("EntityBox_CmdRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Distance.
        /// </summary>
        internal static string EntityBox_fraAvgDist {
            get {
                return ResourceManager.GetString("EntityBox_fraAvgDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Count.
        /// </summary>
        internal static string EntityBox_FraBoxCount {
            get {
                return ResourceManager.GetString("EntityBox_FraBoxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Index.
        /// </summary>
        internal static string EntityBox_fraCameraIndex {
            get {
                return ResourceManager.GetString("EntityBox_fraCameraIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera SubIndex.
        /// </summary>
        internal static string EntityBox_fraCameraSubIndex {
            get {
                return ResourceManager.GetString("EntityBox_fraCameraSubIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDA Section.
        /// </summary>
        internal static string EntityBox_FraDDASection {
            get {
                return ResourceManager.GetString("EntityBox_FraDDASection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDA Death/1-Up Count.
        /// </summary>
        internal static string EntityBox_FraDDASettings {
            get {
                return ResourceManager.GetString("EntityBox_FraDDASettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw List A.
        /// </summary>
        internal static string EntityBox_fraDrawListA {
            get {
                return ResourceManager.GetString("EntityBox_fraDrawListA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw List B.
        /// </summary>
        internal static string EntityBox_fraDrawListB {
            get {
                return ResourceManager.GetString("EntityBox_fraDrawListB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        internal static string EntityBox_fraEIDA {
            get {
                return ResourceManager.GetString("EntityBox_fraEIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        internal static string EntityBox_fraEIDB {
            get {
                return ResourceManager.GetString("EntityBox_fraEIDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities.
        /// </summary>
        internal static string EntityBox_fraEntityA {
            get {
                return ResourceManager.GetString("EntityBox_fraEntityA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities.
        /// </summary>
        internal static string EntityBox_fraEntityB {
            get {
                return ResourceManager.GetString("EntityBox_fraEntityB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field-of-View Timeline.
        /// </summary>
        internal static string EntityBox_fraFOV {
            get {
                return ResourceManager.GetString("EntityBox_fraFOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field-of-View.
        /// </summary>
        internal static string EntityBox_fraFOVFrame {
            get {
                return ResourceManager.GetString("EntityBox_fraFOVFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID &amp;&amp; Look-up ID.
        /// </summary>
        internal static string EntityBox_FraID {
            get {
                return ResourceManager.GetString("EntityBox_FraID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load List A.
        /// </summary>
        internal static string EntityBox_fraLoadListA {
            get {
                return ResourceManager.GetString("EntityBox_fraLoadListA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load List B.
        /// </summary>
        internal static string EntityBox_fraLoadListB {
            get {
                return ResourceManager.GetString("EntityBox_fraLoadListB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Load Lists.
        /// </summary>
        internal static string EntityBox_fraLoadListPayload {
            get {
                return ResourceManager.GetString("EntityBox_fraLoadListPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Mode.
        /// </summary>
        internal static string EntityBox_FraMode {
            get {
                return ResourceManager.GetString("EntityBox_FraMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string EntityBox_FraName {
            get {
                return ResourceManager.GetString("EntityBox_FraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighbors.
        /// </summary>
        internal static string EntityBox_fraNeighbor {
            get {
                return ResourceManager.GetString("EntityBox_fraNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighbor.
        /// </summary>
        internal static string EntityBox_fraNeighborSetting {
            get {
                return ResourceManager.GetString("EntityBox_fraNeighborSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Settings.
        /// </summary>
        internal static string EntityBox_FraOtherSettings {
            get {
                return ResourceManager.GetString("EntityBox_FraOtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position(s).
        /// </summary>
        internal static string EntityBox_FraPosition {
            get {
                return ResourceManager.GetString("EntityBox_FraPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Modifier.
        /// </summary>
        internal static string EntityBox_FraScaling {
            get {
                return ResourceManager.GetString("EntityBox_FraScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument(s).
        /// </summary>
        internal static string EntityBox_FraSettings {
            get {
                return ResourceManager.GetString("EntityBox_FraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort List.
        /// </summary>
        internal static string EntityBox_FraSLST {
            get {
                return ResourceManager.GetString("EntityBox_FraSLST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Trial Reward.
        /// </summary>
        internal static string EntityBox_FraTTReward {
            get {
                return ResourceManager.GetString("EntityBox_FraTTReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &amp;&amp; Subtype.
        /// </summary>
        internal static string EntityBox_FraType {
            get {
                return ResourceManager.GetString("EntityBox_FraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victims.
        /// </summary>
        internal static string EntityBox_FraVictims {
            get {
                return ResourceManager.GetString("EntityBox_FraVictims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth Modifier.
        /// </summary>
        internal static string EntityBox_FraZMod {
            get {
                return ResourceManager.GetString("EntityBox_FraZMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as Number: {0:F3}
        ///as Angle: {1:F}deg
        ///as Time: {2:F}s
        ///as Meters: {3:F3}m.
        /// </summary>
        internal static string EntityBox_lblArgAs {
            get {
                return ResourceManager.GetString("EntityBox_lblArgAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string EntityBox_lblFOVPosition {
            get {
                return ResourceManager.GetString("EntityBox_lblFOVPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string EntityBox_lblMetavalueDrawA {
            get {
                return ResourceManager.GetString("EntityBox_lblMetavalueDrawA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string EntityBox_lblMetavalueDrawB {
            get {
                return ResourceManager.GetString("EntityBox_lblMetavalueDrawB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string EntityBox_lblMetavalueLoadA {
            get {
                return ResourceManager.GetString("EntityBox_lblMetavalueLoadA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string EntityBox_lblMetavalueLoadB {
            get {
                return ResourceManager.GetString("EntityBox_lblMetavalueLoadB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam. Index.
        /// </summary>
        internal static string EntityBox_lblNeighborCamera {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        internal static string EntityBox_lblNeighborFlag {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Type.
        /// </summary>
        internal static string EntityBox_lblNeighborLink {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string EntityBox_lblNeighborPosition {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Index.
        /// </summary>
        internal static string EntityBox_lblNeighborZone {
            get {
                return ResourceManager.GetString("EntityBox_lblNeighborZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string EntityBox_lblPayloadPosition {
            get {
                return ResourceManager.GetString("EntityBox_lblPayloadPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string EntityBox_TabCamera {
            get {
                return ResourceManager.GetString("EntityBox_TabCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Lists.
        /// </summary>
        internal static string EntityBox_TabDrawList {
            get {
                return ResourceManager.GetString("EntityBox_TabDrawList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string EntityBox_TabGeneral {
            get {
                return ResourceManager.GetString("EntityBox_TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Lists.
        /// </summary>
        internal static string EntityBox_TabLoadList {
            get {
                return ResourceManager.GetString("EntityBox_TabLoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string EntityBox_TabSpecial {
            get {
                return ResourceManager.GetString("EntityBox_TabSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort this operation..
        /// </summary>
        internal static string ErrorReporter_Abort {
            get {
                return ResourceManager.GetString("ErrorReporter_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break out to a debugger. (Experts only).
        /// </summary>
        internal static string ErrorReporter_Break {
            get {
                return ResourceManager.GetString("ErrorReporter_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore the error and continue anyway..
        /// </summary>
        internal static string ErrorReporter_Ignore {
            get {
                return ResourceManager.GetString("ErrorReporter_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore the error and all others for this object..
        /// </summary>
        internal static string ErrorReporter_IgnoreAll {
            get {
                return ResourceManager.GetString("ErrorReporter_IgnoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this object, leaving it unprocessed..
        /// </summary>
        internal static string ErrorReporter_Skip {
            get {
                return ResourceManager.GetString("ErrorReporter_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        internal static string ErrorReporter_Title {
            get {
                return ResourceManager.GetString("ErrorReporter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string InputWindow_cmdCancel {
            get {
                return ResourceManager.GetString("InputWindow_cmdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolate Path.
        /// </summary>
        internal static string InterpolatorForm {
            get {
                return ResourceManager.GetString("InterpolatorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string InterpolatorForm_cmdCancel {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string InterpolatorForm_cmdFirst {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string InterpolatorForm_cmdLast {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string InterpolatorForm_cmdNext {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string InterpolatorForm_cmdOK {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string InterpolatorForm_cmdPrev {
            get {
                return ResourceManager.GetString("InterpolatorForm_cmdPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string InterpolatorForm_fraAmount {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/End Position.
        /// </summary>
        internal static string InterpolatorForm_fraBound {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Function.
        /// </summary>
        internal static string InterpolatorForm_fraFunction {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string InterpolatorForm_fraOrder {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        internal static string InterpolatorForm_fraPosition {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tension.
        /// </summary>
        internal static string InterpolatorForm_fraTension {
            get {
                return ResourceManager.GetString("InterpolatorForm_fraTension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Default).
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUE file already exists, will not be modified..
        /// </summary>
        internal static string MakeBIN_CueExists {
            get {
                return ResourceManager.GetString("MakeBIN_CueExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create CUE file: {0}.
        /// </summary>
        internal static string MakeBIN_CueFail {
            get {
                return ResourceManager.GetString("MakeBIN_CueFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created matching CUE file..
        /// </summary>
        internal static string MakeBIN_CueSuccess {
            get {
                return ResourceManager.GetString("MakeBIN_CueSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRNSF returned an error. No region has been applied..
        /// </summary>
        internal static string MakeBIN_DRNSF_Error {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch DRNSF. Reason: {0}.
        /// </summary>
        internal static string MakeBIN_DRNSF_Fail {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching DRNSF to apply selected region....
        /// </summary>
        internal static string MakeBIN_DRNSF_Launch {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region applied successfully..
        /// </summary>
        internal static string MakeBIN_DRNSF_Success {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find DRNSF exe. Please place this in the same directory as CrashEdit..
        /// </summary>
        internal static string MakeBIN_DRNSF_Unavailable {
            get {
                return ResourceManager.GetString("MakeBIN_DRNSF_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making BIN....
        /// </summary>
        internal static string MakeBIN_Making {
            get {
                return ResourceManager.GetString("MakeBIN_Making", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created BIN file without region OK..
        /// </summary>
        internal static string MakeBIN_NoRegOK {
            get {
                return ResourceManager.GetString("MakeBIN_NoRegOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected drive or folder does not contain SYSTEM.CNF or PSX.EXE. At least one of these is required for a bootable PSX CD image. Continue anyway?.
        /// </summary>
        internal static string MakeBIN_NoSystemFiles {
            get {
                return ResourceManager.GetString("MakeBIN_NoSystemFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make BIN.
        /// </summary>
        internal static string MakeBIN_Title {
            get {
                return ResourceManager.GetString("MakeBIN_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Menu_File_Close {
            get {
                return ResourceManager.GetString("Menu_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch NSD.
        /// </summary>
        internal static string Menu_File_PatchNSD {
            get {
                return ResourceManager.GetString("Menu_File_PatchNSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("Menu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Menu_Find {
            get {
                return ResourceManager.GetString("Menu_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry ID.
        /// </summary>
        internal static string Menu_Find_EntryID {
            get {
                return ResourceManager.GetString("Menu_Find_EntryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Name.
        /// </summary>
        internal static string Menu_Find_EntryName {
            get {
                return ResourceManager.GetString("Menu_Find_EntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Menu_Find_Find {
            get {
                return ResourceManager.GetString("Menu_Find_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        internal static string Menu_Find_FindNext {
            get {
                return ResourceManager.GetString("Menu_Find_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Name.
        /// </summary>
        internal static string Menu_Find_ObjectName {
            get {
                return ResourceManager.GetString("Menu_Find_ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current State.
        /// </summary>
        internal static string Menu_Undo_CurrentState {
            get {
                return ResourceManager.GetString("Menu_Undo_CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo {0}.
        /// </summary>
        internal static string Menu_Undo_RedoAction {
            get {
                return ResourceManager.GetString("Menu_Undo_RedoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to redo.
        /// </summary>
        internal static string Menu_Undo_RedoNone {
            get {
                return ResourceManager.GetString("Menu_Undo_RedoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo {0}.
        /// </summary>
        internal static string Menu_Undo_UndoAction {
            get {
                return ResourceManager.GetString("Menu_Undo_UndoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to undo.
        /// </summary>
        internal static string Menu_Undo_UndoNone {
            get {
                return ResourceManager.GetString("Menu_Undo_UndoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Entry.
        /// </summary>
        internal static string NewEntryForm {
            get {
                return ResourceManager.GetString("NewEntryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Name.
        /// </summary>
        internal static string NewEntryForm_fraName {
            get {
                return ResourceManager.GetString("NewEntryForm_fraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Type.
        /// </summary>
        internal static string NewEntryForm_fraType {
            get {
                return ResourceManager.GetString("NewEntryForm_fraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_006 {
            get {
                object obj = ResourceManager.GetObject("objects_006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_006_red {
            get {
                object obj = ResourceManager.GetObject("objects_006_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_006_yellow {
            get {
                object obj = ResourceManager.GetObject("objects_006_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_012 {
            get {
                object obj = ResourceManager.GetObject("objects_012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_012_blue {
            get {
                object obj = ResourceManager.GetObject("objects_012_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_012_code {
            get {
                object obj = ResourceManager.GetObject("objects_012_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_012_crimson {
            get {
                object obj = ResourceManager.GetObject("objects_012_crimson", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_012_gray {
            get {
                object obj = ResourceManager.GetObject("objects_012_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_012_lime {
            get {
                object obj = ResourceManager.GetObject("objects_012_lime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_012_violet {
            get {
                object obj = ResourceManager.GetObject("objects_012_violet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_020 {
            get {
                object obj = ResourceManager.GetObject("objects_020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_028 {
            get {
                object obj = ResourceManager.GetObject("objects_028", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_029 {
            get {
                object obj = ResourceManager.GetObject("objects_029", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_036 {
            get {
                object obj = ResourceManager.GetObject("objects_036", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_037 {
            get {
                object obj = ResourceManager.GetObject("objects_037", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_053_blue {
            get {
                object obj = ResourceManager.GetObject("objects_053_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_053_white {
            get {
                object obj = ResourceManager.GetObject("objects_053_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_070 {
            get {
                object obj = ResourceManager.GetObject("objects_070", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objects_079 {
            get {
                object obj = ResourceManager.GetObject("objects_079", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Features.
        /// </summary>
        internal static string OldMainForm_tbbExtra {
            get {
                return ResourceManager.GetString("OldMainForm_tbbExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert VAB to DLS.
        /// </summary>
        internal static string OldMainForm_tbxConvertVAB {
            get {
                return ResourceManager.GetString("OldMainForm_tbxConvertVAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert VH+VB to DLS.
        /// </summary>
        internal static string OldMainForm_tbxConvertVHVB {
            get {
                return ResourceManager.GetString("OldMainForm_tbxConvertVHVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make BIN (no region).
        /// </summary>
        internal static string OldMainForm_tbxMakeBIN {
            get {
                return ResourceManager.GetString("OldMainForm_tbxMakeBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make BIN (PAL).
        /// </summary>
        internal static string OldMainForm_tbxMakeBINEUR {
            get {
                return ResourceManager.GetString("OldMainForm_tbxMakeBINEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make BIN (NTSC-J).
        /// </summary>
        internal static string OldMainForm_tbxMakeBINJAP {
            get {
                return ResourceManager.GetString("OldMainForm_tbxMakeBINJAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make BIN (NTSC-U/C).
        /// </summary>
        internal static string OldMainForm_tbxMakeBINUSA {
            get {
                return ResourceManager.GetString("OldMainForm_tbxMakeBINUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t figure out NSD filename. Make sure NSF file ends in \&quot;f\&quot; (case-insensitive)!\n\nFOO.NSF -&gt; FOO.NSD\n\n{0} -&gt; ???.
        /// </summary>
        internal static string PatchNSD_Error1 {
            get {
                return ResourceManager.GetString("PatchNSD_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSD patching is not supported for this game version..
        /// </summary>
        internal static string PatchNSD_Error2 {
            get {
                return ResourceManager.GetString("PatchNSD_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch NSD.
        /// </summary>
        internal static string PatchNSD_Title1 {
            get {
                return ResourceManager.GetString("PatchNSD_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loadlist autosorter.
        /// </summary>
        internal static string PatchNSD_Title2 {
            get {
                return ResourceManager.GetString("PatchNSD_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite the NSD file?.
        /// </summary>
        internal static string PatchNSD1 {
            get {
                return ResourceManager.GetString("PatchNSD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to sort all loadlists according to the NSD?.
        /// </summary>
        internal static string PatchNSD2 {
            get {
                return ResourceManager.GetString("PatchNSD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chunk contents in this NSF may have been moved in accordance to the patched NSD and needs to be resaved. Continue?.
        /// </summary>
        internal static string PatchNSD3 {
            get {
                return ResourceManager.GetString("PatchNSD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap People_014 {
            get {
                object obj = ResourceManager.GetObject("People_014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap People_017 {
            get {
                object obj = ResourceManager.GetObject("People_017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap People_020 {
            get {
                object obj = ResourceManager.GetObject("People_020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap People_020_code {
            get {
                object obj = ResourceManager.GetObject("People_020_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap People_020_cyan {
            get {
                object obj = ResourceManager.GetObject("People_020_cyan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap People_020_red {
            get {
                object obj = ResourceManager.GetObject("People_020_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSF filename &apos;{0}&apos; is not appropriate!.
        /// </summary>
        internal static string Playtest_Error1 {
            get {
                return ResourceManager.GetString("Playtest_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t figure out NSD filename. Make sure NSF file ends in \&quot;f\&quot; (case-insensitive)!\n\nFOO.NSF -&gt; FOO.NSD\n\n{0} -&gt; ???.
        /// </summary>
        internal static string Playtest_Error2 {
            get {
                return ResourceManager.GetString("Playtest_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSD file &apos;{0}&apos; does not exist!.
        /// </summary>
        internal static string Playtest_Error3 {
            get {
                return ResourceManager.GetString("Playtest_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find exe file (PSX.EXE, SCUS_123.45, SLES_123.45, etc)..
        /// </summary>
        internal static string Playtest_Error4 {
            get {
                return ResourceManager.GetString("Playtest_Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playtest.
        /// </summary>
        internal static string Playtest_Title {
            get {
                return ResourceManager.GetString("Playtest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Confirmation Prompt.
        /// </summary>
        internal static string Save_ConfirmationPrompt {
            get {
                return ResourceManager.GetString("Save_ConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite this file?.
        /// </summary>
        internal static string SaveNSF {
            get {
                return ResourceManager.GetString("SaveNSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A packing error occurred. The chunk containing entry &apos;{0}&apos; has over 64 KB of data..
        /// </summary>
        internal static string SaveNSF_Error1 {
            get {
                return ResourceManager.GetString("SaveNSF_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IO error occurred.\n\n.
        /// </summary>
        internal static string SaveNSF_Error2 {
            get {
                return ResourceManager.GetString("SaveNSF_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unauthorized access error occurred.\n\n.
        /// </summary>
        internal static string SaveNSF_Error3 {
            get {
                return ResourceManager.GetString("SaveNSF_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveNSF_Title {
            get {
                return ResourceManager.GetString("SaveNSF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; has not been saved since it was last modified. Continue anyway?.
        /// </summary>
        internal static string Text_CloseDirtyFilePrompt {
            get {
                return ResourceManager.GetString("Text_CloseDirtyFilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Mode.
        /// </summary>
        internal static string TextureViewer_groupBox1 {
            get {
                return ResourceManager.GetString("TextureViewer_groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend Mode.
        /// </summary>
        internal static string TextureViewer_groupBox2 {
            get {
                return ResourceManager.GetString("TextureViewer_groupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string TextureViewer_groupBox4 {
            get {
                return ResourceManager.GetString("TextureViewer_groupBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string TextureViewer_groupBox5 {
            get {
                return ResourceManager.GetString("TextureViewer_groupBox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Toolbar_Close {
            get {
                return ResourceManager.GetString("Toolbar_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Toolbar_Find {
            get {
                return ResourceManager.GetString("Toolbar_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        internal static string Toolbar_FindNext {
            get {
                return ResourceManager.GetString("Toolbar_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto EID.
        /// </summary>
        internal static string Toolbar_GotoEID {
            get {
                return ResourceManager.GetString("Toolbar_GotoEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Toolbar_Open {
            get {
                return ResourceManager.GetString("Toolbar_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch NSD.
        /// </summary>
        internal static string Toolbar_PatchNSD {
            get {
                return ResourceManager.GetString("Toolbar_PatchNSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo {0}.
        /// </summary>
        internal static string Toolbar_RedoAction {
            get {
                return ResourceManager.GetString("Toolbar_RedoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Toolbar_RedoNone {
            get {
                return ResourceManager.GetString("Toolbar_RedoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Toolbar_Save {
            get {
                return ResourceManager.GetString("Toolbar_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo {0}.
        /// </summary>
        internal static string Toolbar_UndoAction {
            get {
                return ResourceManager.GetString("Toolbar_UndoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Toolbar_UndoNone {
            get {
                return ResourceManager.GetString("Toolbar_UndoNone", resourceCulture);
            }
        }
    }
}
